import re
from enum import Enum
from dataclasses import dataclass
from typing import Dict, Any, List, Tuple, Optional
try:
    from document.pdf_extractor import ExtractedDocument
except ImportError:
    try:
        from backend.document.pdf_extractor import ExtractedDocument
    except ImportError:
        from ..document.pdf_extractor import ExtractedDocument

class GroundingStatus(str, Enum):
    VERIFIED = "verified"
    HIGH_CONFIDENCE = "high_confidence"
    NEEDS_REVIEW = "needs_review"
    UNVERIFIED = "unverified"

@dataclass
class GroundingReport:
    status: GroundingStatus
    similarity_score: float
    confidence_score: int
    reasoning: str

class EvidenceValidator:
    """Validates that claims generated by LLMs are grounded in actual source document text."""

    def normalize(self, text: str) -> str:
        # Lowercase and collapse all whitespace/punctuation for flexible matching
        return re.sub(r'[^a-z0-9]', '', text.lower())

    def validate_insight(self, insight: Dict[str, Any], document: ExtractedDocument) -> Dict[str, Any]:
        validated = dict(insight)
        source = insight.get("source", {})
        claimed_page = source.get("page", 1)
        claimed_text = source.get("text", "")

        if not claimed_text:
            if "verification" not in validated:
                validated["verification"] = {}
            validated["verification"]["status"] = "needs_review"
            validated["verification"]["reasoning"] = "No direct source quotation was provided."
            return validated

        norm_claimed = self.normalize(claimed_text)

        # Check target page first
        page_match = False
        for page in document.pages:
            if page.page_number == claimed_page:
                norm_page = self.normalize(page.text)
                if norm_claimed in norm_page or self._contains_key_tokens(norm_claimed, norm_page):
                    page_match = True
                    break

        # If not found on claimed page, check whole document
        doc_match = page_match
        if not doc_match:
            norm_full = self.normalize(document.full_text)
            if norm_claimed in norm_full or self._contains_key_tokens(norm_claimed, norm_full):
                doc_match = True

        if "verification" not in validated:
            validated["verification"] = {}

        if not doc_match:
            # Ungrounded claim detected!
            validated["verification"]["status"] = "needs_review"
            validated["verification"]["reasoning"] = (
                "Grounding check flagged: Cited evidence excerpt could not be directly matched against document text. Please verify with doctor."
            )
        else:
            # Verified ground exists
            if validated.get("verification", {}).get("status") != "needs_review":
                validated["verification"]["status"] = "consistent"

        return validated

    def _contains_key_tokens(self, claimed: str, source: str) -> bool:
        if len(claimed) < 10:
            return claimed in source
        chunks = [claimed[i:i+6] for i in range(0, len(claimed)-6, 4)]
        if not chunks:
            return False
        matches = sum(1 for c in chunks if c in source)
        return (matches / len(chunks)) >= 0.70


def validate_finding_grounding(finding: Dict[str, Any], source_text: str) -> GroundingReport:
    """Evaluates whether a finding's source quote is present in the source text."""
    validator = EvidenceValidator()
    quote = finding.get("sourceQuote") or finding.get("source", {}).get("text", "")

    if not quote:
        return GroundingReport(
            status=GroundingStatus.UNVERIFIED,
            similarity_score=0.0,
            confidence_score=30,
            reasoning="No evidence quote provided to ground this insight.",
        )

    norm_quote = validator.normalize(quote)
    norm_source = validator.normalize(source_text)

    if norm_quote in norm_source:
        return GroundingReport(
            status=GroundingStatus.VERIFIED,
            similarity_score=1.0,
            confidence_score=finding.get("confidenceScore", 95),
            reasoning="Exact verbatim match located in source text.",
        )

    if validator._contains_key_tokens(norm_quote, norm_source):
        return GroundingReport(
            status=GroundingStatus.HIGH_CONFIDENCE,
            similarity_score=0.85,
            confidence_score=finding.get("confidenceScore", 90),
            reasoning="High-confidence token match located in source text.",
        )

    return GroundingReport(
        status=GroundingStatus.UNVERIFIED,
        similarity_score=0.2,
        confidence_score=35,
        reasoning="Quoted evidence was not found in source text.",
    )


def validate_analysis_claims(findings: List[Dict[str, Any]], source_text: str) -> Tuple[List[Dict[str, Any]], int]:
    """Validates an entire batch of findings against source text, computing overall confidence."""
    verified_list = []
    total_conf = 0

    for f in findings:
        rep = validate_finding_grounding(f, source_text)
        updated = dict(f)
        updated["verificationStatus"] = rep.status.value
        updated["confidenceScore"] = rep.confidence_score
        updated["groundingReasoning"] = rep.reasoning
        total_conf += rep.confidence_score
        verified_list.append(updated)

    avg_conf = round(total_conf / len(findings)) if findings else 90
    return verified_list, avg_conf
